export const pagesClassesMapping = {
    ContactPageClass: 'ContactPage',
    Error404PageClass: 'Error',
    FeedbackSysPageClass: 'FeedbackSys',
    HomePageClass: 'Home',
    HomeworksPageClass: 'Homeworks',
    LoginSysPageClass: 'LoginSys',
    TeachersTeamPageClass: 'TeachersTeam',
    StaffTeamPageClass: 'StaffTeam',
    SchedulesPageClass: 'Schedules',
    TeacherDetailsPageClass: 'TeacherDetails',
    UserPageClass: 'UserPage',
}

export const appClassesMapping = {
    SpaceForPhoneClass: 'SpaceForPhone',
    BreathingSpaceMediumClass: 'BreathingSpaceMedium',
    BreathingSpaceSmallClass: 'BreathingSpaceSmall',
    BreathingSpaceHugeClass: 'BreathingSpaceHuge',
    FlexContainerClass: 'FlexContainer',
    ClipUpWallpaperClass: 'ClipUpWallpaper',
    GrayWallpaperClipDownClass: 'GrayWallpaperClipDown',
    FormClass: 'Form',
    PaddingClass: 'Padding',
    SpaceForLargeBreakPointClass: 'SpaceForLargeBreakPoint',
    ActiveClass: 'Active',
    BorderedButtonClass: 'BorderedButton',
    MediumPaddingClass: 'MediumPadding',
    SmallPaddingClass: 'SmallPadding',
}