export const pagesClassesMapping = {
    ContactPageClass: 'ContactPage',
    Error404PageClass: 'Error',
    FeedbackSysPageClass: 'FeedbackSys',
    HomePageClass: 'Home',
    HomeworksPageClass: 'Homeworks',
    LoginSysPageClass: 'LoginSys',
    TeachersTeamPageClass: 'TeachersTeam',
    StaffTeamPageClass: 'StaffTeam',
    SchedulesPageClass: 'Schedules',
    TeacherDetailsPageClass: 'TeacherDetails',
    UserPageClass: 'UserPage',
}

export const componentsClassesMapping = {
    DisplayExpectationsClass: 'DisplayExpectations',
    ShineMessageClass: 'ShineMessage',
    ShineMessageLinkClass: 'ShineMessageLink',
    TeacherDetailsClass: 'TeacherDetails',
    CellClass: 'Cell',
    DataForTeacherClass: 'DataForTeacher',
    SocialDetailsClass: 'social-details',
    MemberDetailsClass: 'memberDetails',
    HalfHeroCardClass: 'HalfHeroCard',
    NavigationClass: 'Navigation',
    NormalNavigationActiveClass: 'NormalNavigation Active',
    NormalNavigationSimpleClass: 'NormalNavigation Simple',
    ItemClass: 'Item',
    ItemActiveMenuClass: 'Item ActiveMenuItem',
    ItemActiveMenuPhoneHiddenClass: 'Item ActiveMenuItem PhoneHidden',
    ItemPhoneHiddenClass: 'Item PhoneHidden',
    LogoClass: 'Logo',
    ItemsRightAlignClass: 'ItemsRightAlign',
    DropdownClass: 'Dropdown',
    UserDropButtonClass: 'User DropButton',
    DropdownContentClass: 'DropdownContent',
    PhoneNavigationClass: 'PhoneNavigation',
    HeroContainerClass: 'HeroContainer',
    WelcomeMessageClass: 'WelcomeMessage',
    HeroButtonsClass: 'HeroButtons',
    NavigationButtonsClass: 'NavigationButtons',
    ParallaxContainerClass: 'ParallaxContainer',
    GradientClass: 'Gradient',
    ParallaxBackgroundClass: 'ParallaxBackground',
    HomeworkClass: 'Homework',
    HomeworkBorderClass: 'HomeworkBorder',
    ScheduleClass: 'Schedule',
    ScheduleBorderClass: 'ScheduleBorder',
    ScrollButtonClass: 'ScrollButton',
    UserNameClass: 'UserName',
    DelimitationBorderClass: 'DelimitationBorder',
    DepartmentClass: 'Department',
    SocialMediaPresenceClass: 'SocialMediaPresence',
}

export const appClassesMapping = {
    SpaceForPhoneClass: 'SpaceForPhone',
    BreathingSpaceMediumClass: 'BreathingSpaceMedium',
    BreathingSpaceSmallClass: 'BreathingSpaceSmall',
    BreathingSpaceHugeClass: 'BreathingSpaceHuge',
    FlexContainerClass: 'FlexContainer',
    ClipUpWallpaperClass: 'ClipUpWallpaper',
    GrayWallpaperClipDownClass: 'GrayWallpaperClipDown',
    FormClass: 'Form',
    PaddingClass: 'Padding',
    SpaceForLargeBreakPointClass: 'SpaceForLargeBreakPoint',
    ActiveClass: 'Active',
    BorderedButtonClass: 'BorderedButton',
    MediumPaddingClass: 'MediumPadding',
    SmallPaddingClass: 'SmallPadding',
}